---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    app: fileserver
spec:
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
  containers:
  - name: gop-fileserver
    image: kodekloud/fileserver 
    ports:
    - containerPort: 8080
    volumeMounts:
      - mountPath: /web
        name: data-store
---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  selector:
    app: fileserver
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31200