---
apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret 
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_DATABASE: ZHJ1cGFsLWRhdGFiYXNl
  MYSQL_USER: cm9vdA==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  capacity: 
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /drupal-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  capacity: 
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /drupal-mysql-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
              claimName: drupal-mysql-pvc
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            subPath: dbdata
            name: data
        env:
          - name: MYSQL_DATABASE
            valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: drupal-mysql-secret
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: drupal-mysql-secret
          - name: MYSQL_USER
            valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: drupal-mysql-secret
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service 
spec:
  selector:
    app: drupal-mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
              claimName: drupal-pvc
      initContainers:
      - name: init-sites-volume
        image: drupal:8.6
        volumeMounts:
          - mountPath: /data
            name: data
        command: [ "/bin/bash", "-c" ]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
      containers:
      - name: drupal
        image: drupal:8.6
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html/modules
            subPath: modules
            name: data
          - mountPath: /var/www/html/profiles
            subPath: profiles
            name: data
          - mountPath: /var/www/html/sites
            subPath: sites
            name: data
          - mountPath: /var/www/html/themes
            subPath: themes
            name: data
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  selector:
    app: drupal
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30095